const S3_DELETE_BATCH_LIMIT = 1000;
const DEFAULT_UPLOAD_EXPIRES_IN = 300;
const DEFAULT_MAX_FILE_SIZE = 10 * 1024 * 1024;

export {
  DEFAULT_MAX_FILE_SIZE,
  DEFAULT_UPLOAD_EXPIRES_IN,
  S3_DELETE_BATCH_LIMIT,
};
