const AUTO_SNAPSHOT_DELAY = 60 * 60 * 1000;
const PAGE_VERSIONS_DEFAULT_LIMIT = 20;
const PAGE_VERSIONS_MAX_LIMIT = 50;

export {
  AUTO_SNAPSHOT_DELAY,
  PAGE_VERSIONS_DEFAULT_LIMIT,
  PAGE_VERSIONS_MAX_LIMIT,
};
